package entite;
// Generated 18 mars 2016 10:01:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Emprunt generated by hbm2java
 */
public class Emprunt  implements java.io.Serializable {


     private int idEmprunt;
     private Livre livre;
     private Utilisateur utilisateur;
     private int dateDebut;
     private Date dateFin;

    public Emprunt() {
    }

    public Emprunt(int idEmprunt, Livre livre, Utilisateur utilisateur, int dateDebut, Date dateFin) {
       this.idEmprunt = idEmprunt;
       this.livre = livre;
       this.utilisateur = utilisateur;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
    }
   
    public int getIdEmprunt() {
        return this.idEmprunt;
    }
    
    public void setIdEmprunt(int idEmprunt) {
        this.idEmprunt = idEmprunt;
    }
    public Livre getLivre() {
        return this.livre;
    }
    
    public void setLivre(Livre livre) {
        this.livre = livre;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public int getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(int dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


