package entite;
// Generated 18 mars 2016 10:01:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Livre generated by hbm2java
 */
public class Livre  implements java.io.Serializable {


     private int idLivre;
     private String titreLivre;
     private String auteurLivre;
     private String isbn;
     private String participantsLivre;
     private String editeurLivre;
     private Date dateEdition;
     private String lieuEdition;
     private String collection;
     private int nbPages;
     private Float hauteurLivre;
     private Float largeurLivre;
     private Float profondeurLivre;
     private String couleurNb;
     private String langueLivre;
     private float classificationDewey;
     private String resumeLivre;
     private String notesLivre;
     private String coteLivre;
     private String secteur;
     private String motsClef;
     private Set emprunts = new HashSet(0);

    public Livre() {
    }

	
    public Livre(int idLivre, String titreLivre, String auteurLivre, String isbn, String participantsLivre, String editeurLivre, Date dateEdition, String lieuEdition, String collection, int nbPages, Float hauteurLivre, Float largeurLivre, Float profondeurLivre, String couleurNb, String langueLivre, float classificationDewey, String resumeLivre, String notesLivre, String coteLivre, String secteur, String motsClef) {
        this.idLivre = idLivre;
        this.titreLivre = titreLivre;
        this.auteurLivre = auteurLivre;
        this.isbn = isbn;
        this.participantsLivre = participantsLivre;
        this.editeurLivre = editeurLivre;
        this.dateEdition = dateEdition;
        this.lieuEdition = lieuEdition;
        this.collection = collection;
        this.nbPages = nbPages;
        this.hauteurLivre = hauteurLivre;
        this.largeurLivre = largeurLivre;
        this.profondeurLivre = profondeurLivre;
        this.couleurNb = couleurNb;
        this.langueLivre = langueLivre;
        this.classificationDewey = classificationDewey;
        this.resumeLivre = resumeLivre;
        this.notesLivre = notesLivre;
        this.coteLivre = coteLivre;
        this.secteur = secteur;
        this.motsClef = motsClef;
    }
    public Livre(int idLivre, String titreLivre, String auteurLivre, String isbn, String participantsLivre, String editeurLivre, Date dateEdition, String lieuEdition, String collection, int nbPages, Float hauteurLivre, Float largeurLivre, Float profondeurLivre, String couleurNb, String langueLivre, float classificationDewey, String resumeLivre, String notesLivre, String coteLivre, String secteur, String motsClef, Set emprunts) {
       this.idLivre = idLivre;
       this.titreLivre = titreLivre;
       this.auteurLivre = auteurLivre;
       this.isbn = isbn;
       this.participantsLivre = participantsLivre;
       this.editeurLivre = editeurLivre;
       this.dateEdition = dateEdition;
       this.lieuEdition = lieuEdition;
       this.collection = collection;
       this.nbPages = nbPages;
       this.hauteurLivre = hauteurLivre;
       this.largeurLivre = largeurLivre;
       this.profondeurLivre = profondeurLivre;
       this.couleurNb = couleurNb;
       this.langueLivre = langueLivre;
       this.classificationDewey = classificationDewey;
       this.resumeLivre = resumeLivre;
       this.notesLivre = notesLivre;
       this.coteLivre = coteLivre;
       this.secteur = secteur;
       this.motsClef = motsClef;
       this.emprunts = emprunts;
    }
   
    public int getIdLivre() {
        return this.idLivre;
    }
    
    public void setIdLivre(int idLivre) {
        this.idLivre = idLivre;
    }
    public String getTitreLivre() {
        return this.titreLivre;
    }
    
    public void setTitreLivre(String titreLivre) {
        this.titreLivre = titreLivre;
    }
    public String getAuteurLivre() {
        return this.auteurLivre;
    }
    
    public void setAuteurLivre(String auteurLivre) {
        this.auteurLivre = auteurLivre;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getParticipantsLivre() {
        return this.participantsLivre;
    }
    
    public void setParticipantsLivre(String participantsLivre) {
        this.participantsLivre = participantsLivre;
    }
    public String getEditeurLivre() {
        return this.editeurLivre;
    }
    
    public void setEditeurLivre(String editeurLivre) {
        this.editeurLivre = editeurLivre;
    }
    public Date getDateEdition() {
        return this.dateEdition;
    }
    
    public void setDateEdition(Date dateEdition) {
        this.dateEdition = dateEdition;
    }
    public String getLieuEdition() {
        return this.lieuEdition;
    }
    
    public void setLieuEdition(String lieuEdition) {
        this.lieuEdition = lieuEdition;
    }
    public String getCollection() {
        return this.collection;
    }
    
    public void setCollection(String collection) {
        this.collection = collection;
    }
    public int getNbPages() {
        return this.nbPages;
    }
    
    public void setNbPages(int nbPages) {
        this.nbPages = nbPages;
    }
    public Float getHauteurLivre() {
        return this.hauteurLivre;
    }
    
    public void setHauteurLivre(Float hauteurLivre) {
        this.hauteurLivre = hauteurLivre;
    }
    public Float getLargeurLivre() {
        return this.largeurLivre;
    }
    
    public void setLargeurLivre(Float largeurLivre) {
        this.largeurLivre = largeurLivre;
    }
    public Float getProfondeurLivre() {
        return this.profondeurLivre;
    }
    
    public void setProfondeurLivre(Float profondeurLivre) {
        this.profondeurLivre = profondeurLivre;
    }
    public String getCouleurNb() {
        return this.couleurNb;
    }
    
    public void setCouleurNb(String couleurNb) {
        this.couleurNb = couleurNb;
    }
    public String getLangueLivre() {
        return this.langueLivre;
    }
    
    public void setLangueLivre(String langueLivre) {
        this.langueLivre = langueLivre;
    }
    public float getClassificationDewey() {
        return this.classificationDewey;
    }
    
    public void setClassificationDewey(float classificationDewey) {
        this.classificationDewey = classificationDewey;
    }
    public String getResumeLivre() {
        return this.resumeLivre;
    }
    
    public void setResumeLivre(String resumeLivre) {
        this.resumeLivre = resumeLivre;
    }
    public String getNotesLivre() {
        return this.notesLivre;
    }
    
    public void setNotesLivre(String notesLivre) {
        this.notesLivre = notesLivre;
    }
    public String getCoteLivre() {
        return this.coteLivre;
    }
    
    public void setCoteLivre(String coteLivre) {
        this.coteLivre = coteLivre;
    }
    public String getSecteur() {
        return this.secteur;
    }
    
    public void setSecteur(String secteur) {
        this.secteur = secteur;
    }
    public String getMotsClef() {
        return this.motsClef;
    }
    
    public void setMotsClef(String motsClef) {
        this.motsClef = motsClef;
    }
    public Set getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set emprunts) {
        this.emprunts = emprunts;
    }




}


