package entite;
// Generated 18 mars 2016 10:01:01 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private Utilisateur utilisateur;
     private String password;
     private int enabled;
     private Authorities authorities;

    public Users() {
    }

	
    public Users(String username, Utilisateur utilisateur, String password, int enabled) {
        this.username = username;
        this.utilisateur = utilisateur;
        this.password = password;
        this.enabled = enabled;
    }
    public Users(String username, Utilisateur utilisateur, String password, int enabled, Authorities authorities) {
       this.username = username;
       this.utilisateur = utilisateur;
       this.password = password;
       this.enabled = enabled;
       this.authorities = authorities;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
    public Authorities getAuthorities() {
        return this.authorities;
    }
    
    public void setAuthorities(Authorities authorities) {
        this.authorities = authorities;
    }




}


