package entite;
// Generated 18 mars 2016 10:01:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private int idUtilisateur;
     private String nomUtilisateur;
     private String prenomUtilisateur;
     private String sexeUtilisateur;
     private Date dateNaissance;
     private String adresseUtlisateur;
     private String telephoneUtilisateur;
     private String mailUtilisateur;
     private boolean bibiliothecaire;
     private Set userses = new HashSet(0);
     private Set emprunts = new HashSet(0);

    public Utilisateur() {
    }

	
    public Utilisateur(int idUtilisateur, String nomUtilisateur, String prenomUtilisateur, String sexeUtilisateur, Date dateNaissance, String adresseUtlisateur, String telephoneUtilisateur, String mailUtilisateur, boolean bibiliothecaire) {
        this.idUtilisateur = idUtilisateur;
        this.nomUtilisateur = nomUtilisateur;
        this.prenomUtilisateur = prenomUtilisateur;
        this.sexeUtilisateur = sexeUtilisateur;
        this.dateNaissance = dateNaissance;
        this.adresseUtlisateur = adresseUtlisateur;
        this.telephoneUtilisateur = telephoneUtilisateur;
        this.mailUtilisateur = mailUtilisateur;
        this.bibiliothecaire = bibiliothecaire;
    }
    public Utilisateur(int idUtilisateur, String nomUtilisateur, String prenomUtilisateur, String sexeUtilisateur, Date dateNaissance, String adresseUtlisateur, String telephoneUtilisateur, String mailUtilisateur, boolean bibiliothecaire, Set userses, Set emprunts) {
       this.idUtilisateur = idUtilisateur;
       this.nomUtilisateur = nomUtilisateur;
       this.prenomUtilisateur = prenomUtilisateur;
       this.sexeUtilisateur = sexeUtilisateur;
       this.dateNaissance = dateNaissance;
       this.adresseUtlisateur = adresseUtlisateur;
       this.telephoneUtilisateur = telephoneUtilisateur;
       this.mailUtilisateur = mailUtilisateur;
       this.bibiliothecaire = bibiliothecaire;
       this.userses = userses;
       this.emprunts = emprunts;
    }
   
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }
    public String getNomUtilisateur() {
        return this.nomUtilisateur;
    }
    
    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }
    public String getPrenomUtilisateur() {
        return this.prenomUtilisateur;
    }
    
    public void setPrenomUtilisateur(String prenomUtilisateur) {
        this.prenomUtilisateur = prenomUtilisateur;
    }
    public String getSexeUtilisateur() {
        return this.sexeUtilisateur;
    }
    
    public void setSexeUtilisateur(String sexeUtilisateur) {
        this.sexeUtilisateur = sexeUtilisateur;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    public String getAdresseUtlisateur() {
        return this.adresseUtlisateur;
    }
    
    public void setAdresseUtlisateur(String adresseUtlisateur) {
        this.adresseUtlisateur = adresseUtlisateur;
    }
    public String getTelephoneUtilisateur() {
        return this.telephoneUtilisateur;
    }
    
    public void setTelephoneUtilisateur(String telephoneUtilisateur) {
        this.telephoneUtilisateur = telephoneUtilisateur;
    }
    public String getMailUtilisateur() {
        return this.mailUtilisateur;
    }
    
    public void setMailUtilisateur(String mailUtilisateur) {
        this.mailUtilisateur = mailUtilisateur;
    }
    public boolean isBibiliothecaire() {
        return this.bibiliothecaire;
    }
    
    public void setBibiliothecaire(boolean bibiliothecaire) {
        this.bibiliothecaire = bibiliothecaire;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
    public Set getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set emprunts) {
        this.emprunts = emprunts;
    }




}


